### ISSUE TITLE
igc namespace fails to create a project in OpenShift

### ISSUE THREAD

**Issue by davesteinberg** [ibm-garage-cloud/ibm-garage-cloud-cli#2]
In the MOOC environment on IBM Cloud, I'm finding that `igc namespace` fails to create a project/namespace in OpenShift. I can create a one manually with the OpenShift web UI or the `oc` CLI, and then `igc namespace` will successfully prepare it with configmaps and secrets. 

But, if the namespace doesn't already exist, `igc namespace` fails with an error suggesting that I lack permissions to do so:

```
$ igc namespace dev-ds
⠧ Creating namespace: dev-dsError preparing namespace Error: namespaces is forbidden: User "IAM#davidms@ca.ibm.com" cannot create namespaces at the cluster scope: no RBAC policy matched
    at /Users/dave/.asdf/installs/nodejs/12.13.0/.npm/lib/node_modules/@garage-catalyst/ibm-garage-cloud-cli/node_modules/kubernetes-client/backends/request/client.js:231:25
    at Request._callback (/Users/dave/.asdf/installs/nodejs/12.13.0/.npm/lib/node_modules/@garage-catalyst/ibm-garage-cloud-cli/node_modules/kubernetes-client/backends/request/client.js:168:14)
    at Request.self.callback (/Users/dave/.asdf/installs/nodejs/12.13.0/.npm/lib/node_modules/@garage-catalyst/ibm-garage-cloud-cli/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/Users/dave/.asdf/installs/nodejs/12.13.0/.npm/lib/node_modules/@garage-catalyst/ibm-garage-cloud-cli/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/Users/dave/.asdf/installs/nodejs/12.13.0/.npm/lib/node_modules/@garage-catalyst/ibm-garage-cloud-cli/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12) {
  code: 403,
  statusCode: 403
}
```

**Comment by mjperrins** [comment]
Can you retest this, this may have been an issue with RBAC at the time ? @seansund can we check that the error returned to the user is a little clearer etc

**Comment by davesteinberg** [comment]
I just retested: seems like this is working now.
