### ISSUE TITLE
oc sync --dev fails when user is a normal authenticated user

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-cloud/ibm-garage-cloud-cli#69]
Created a none admin user `user1`
This user can self-provision namespaces but only using `oc new-project my-project` not `oc create ns my-project`

The CLI should create a `project` for the user when using OCP, and create ns when using IKS

```
csantana@cloudshell:~/app$ oc sync $USERNAME-dev --dev
Setting up namespace user1-dev and serviceAccount default
⠇ Creating namespace: user1-devError preparing namespace { Error: namespaces is forbidden: User "user1" cannot create resource "namespaces" in API group "" at the cluster scope
    at _request (/home/csantana/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/kubernetes-client/backends/request/client.js:231:25)
    at Request.request [as _callback] (/home/csantana/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/kubernetes-client/backends/request/client.js:168:14)
    at Request.self.callback (/home/csantana/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/csantana/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/csantana/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12) code: 403, statusCode: 403 }
```

**Comment by csantanapr** [comment]
The minimum access a developer user should have for `oc pipeline` on the project he is admin, is to be able read configmaps, secrets, pipelines, and tasks from the `tools` namespace.
In addition, should be able to read crds (type) 
Here is a script we use for the workshop to setup the toolkit group that developer get added
https://github.com/ibm-garage-cloud/cloud-native-toolkit-workshop/blob/main/scripts/12-ocp-group-toolkit.sh

**Comment by csantanapr** [comment]
this is fixed now
